module.exports.getInfoByOAuth = (info) => {
  //   login: 'Aimee1608',
  //   id: 21167450,
  //   node_id: 'MDQ6VXNlcjIxMTY3NDUw',
  //   avatar_url: 'https://avatars.githubusercontent.com/u/21167450?v=4',
  //   gravatar_id: '',
  //   url: 'https://api.github.com/users/Aimee1608',
  //   html_url: 'https://github.com/Aimee1608',
  //   followers_url: 'https://api.github.com/users/Aimee1608/followers',
  //   following_url: 'https://api.github.com/users/Aimee1608/following{/other_user}',
  //   gists_url: 'https://api.github.com/users/Aimee1608/gists{/gist_id}',
  //   starred_url: 'https://api.github.com/users/Aimee1608/starred{/owner}{/repo}',
  //   subscriptions_url: 'https://api.github.com/users/Aimee1608/subscriptions',
  //   organizations_url: 'https://api.github.com/users/Aimee1608/orgs',
  //   repos_url: 'https://api.github.com/users/Aimee1608/repos',
  //   events_url: 'https://api.github.com/users/Aimee1608/events{/privacy}',
  //   received_events_url: 'https://api.github.com/users/Aimee1608/received_events',
  //   type: 'User',
  //   site_admin: false,
  //   name: 'Aimee',
  //   company: null,
  //   blog: 'http://mangoya.cn/',
  //   location: null,
  //   email: 'shuigongqian@sina.com',
  //   hireable: true,
  //   bio: 'Write the Code. Change the World.',
  //   twitter_username: null,
  //   public_repos: 53,
  //   public_gists: 0,
  //   followers: 102,
  //   following: 1,
  //   created_at: '2016-08-22T06:07:35Z',
  //   updated_at: '2021-07-27T14:30:13Z'

};
